rmdir /S /Q "C:\Program Files\Vim\vimfiles\bundle"
rmdir /S /Q "C:\Program Files\Vim\vimfiles\vimycm"
del "C:\Program Files\Vim\_vimrc"
copy vimrc "C:\Program Files\Vim\_vimrc"
xcopy /S /E /H bundle "C:\Program Files\Vim\vimfiles\bundle\"
xcopy /S /E /H Scripts\vimycm "C:\Program Files\Vim\vimfiles\vimycm\"
