rmdir /S /Q "%USERPROFILE%\vimfiles\bundle"
rmdir /S /Q "%USERPROFILE%\vimfiles\vimycm"
del "%USERPROFILE%\_vimrc"
copy vimrc "%USERPROFILE%\_vimrc"
xcopy /S /E /H bundle  "%USERPROFILE%\vimfiles\bundle\"
xcopy /S /E /H Scripts\vimycm "%USERPROFILE%\vimfiles\vimycm\"
